repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.4.0
    hooks:
      - {id: trailing-whitespace, exclude: init_db/}
      - {id: end-of-file-fixer, exclude: init_db/}
      - {
        id: no-commit-to-branch,
        args: ["--branch", master],
        exclude: init_db/
      }
  - repo: "https://github.com/PyCQA/flake8"
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: init_db/
  - repo: "https://github.com/PyCQA/isort"
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: init_db/
  - repo: "https://github.com/psf/black"
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.10
        exclude: init_db/
